Document supported environment variables
iterative/studio-selfhosted pull request #14
Opened 2022-09-06 08:52 UTC by JIoJIaJIu

## Context

Needs to improve documentation pointing supported environment variables for configuring Studio

2022-09-06 08:57 UTC, mjasion approved these changes

2022-09-06 08:57 UTC, mjasion commented on docs/env.md
> +
What do you think of naming this as  `### General` section?

2022-09-06 08:57 UTC, mjasion commented on docs/env.md
> +#### GITHUB_APP_NAME
If in backend is `H3` paragraph  for `Github` Gitlab etc, I would also do it in the frontend. WDYT? 

Maybe here should be `Repositories` or something more gerenal

2022-09-06 14:37 UTC, jesper7 requested changes
Great initiative!

2022-09-06 14:37 UTC, jesper7 commented on docs/env.md
> +# Environment variables
I think it's better to use a table for each section, i.e.

## GitLab

|Name|Default value|Description|
|---|---|---|
|GITLAB_CLIENT_ID|   |   |
|GITLAB_SECRET_KEY|   |   |
|GITLAB_URL|https://gitlab.com|   |
|GITLAB_WEBHOOK_URL|   |   |
|GITLAB_WEBHOOK_SECRET|   |   |

2022-09-09 06:17 UTC, mvshmakov commented
@JIoJIaJIu could you please add `PLAUSIBLE_DATA_DOMAIN` here as well? It was introduced pretty recently: https://github.com/iterative/studio/pull/4257.

2023-01-04 09:49 UTC, closed without merging

2023-01-04 09:52 UTC, mjasion commented
We are closing this PR because we don't want to support studio-selfhosted. We will be migrating to helm-charts soon.